"""empty message

Revision ID: 1598d8f81ed3
Revises: 83377cf6085
Create Date: 2015-02-27 22:58:28.441469

"""

# revision identifiers, used by Alembic.
revision = '1598d8f81ed3'
down_revision = '83377cf6085'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('updated_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_on')
    op.drop_column('task', 'created_on')
    ### end Alembic commands ###
